//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capa_Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cotizacion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cotizacion()
        {
            this.Detalle_cotizacion = new HashSet<Detalle_cotizacion>();
        }
    
        public int num_cotizacion { get; set; }
        public Nullable<int> Id_emp { get; set; }
        public Nullable<int> id_cli { get; set; }
        public Nullable<System.DateTime> fecha_cotizacion { get; set; }
        public Nullable<decimal> total { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Empleados Empleados { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Detalle_cotizacion> Detalle_cotizacion { get; set; }
    }
}
