//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capa_Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Detalle_cotizacion
    {
        public int id_detalle_cotizacion { get; set; }
        public Nullable<int> num_cotizacion { get; set; }
        public Nullable<int> id_producto { get; set; }
        public Nullable<int> id_cli { get; set; }
        public Nullable<int> cantidad { get; set; }
        public Nullable<decimal> precio_uni { get; set; }
        public Nullable<decimal> total { get; set; }
    
        public virtual Cotizacion Cotizacion { get; set; }
        public virtual Producto Producto { get; set; }
    }
}
