//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capa_Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empleados
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Empleados()
        {
            this.Cotizacion = new HashSet<Cotizacion>();
        }
    
        public int ID_emp { get; set; }
        public string nombre_emp { get; set; }
        public string apellido_emp { get; set; }
        public string direccion_emp { get; set; }
        public string telefono_emp { get; set; }
        public string correo_emp { get; set; }
        public string nacimiento_emp { get; set; }
        public int id_cargo { get; set; }
        public Nullable<int> id_rol { get; set; }
    
        public virtual Cargos Cargos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cotizacion> Cotizacion { get; set; }
        public virtual Rol Rol { get; set; }
    }
}
