//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capa_Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Facturas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Facturas()
        {
            this.Detalle_Factura = new HashSet<Detalle_Factura>();
            this.Pagos = new HashSet<Pagos>();
        }
    
        public int id_factura { get; set; }
        public Nullable<int> id_cli { get; set; }
        public Nullable<int> num_cotizacion { get; set; }
        public Nullable<System.DateTime> fecha_venta { get; set; }
        public string tipo { get; set; }
        public Nullable<bool> credito { get; set; }
        public Nullable<int> id_proveedor { get; set; }
        public Nullable<int> id_tipo_pago { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Detalle_Factura> Detalle_Factura { get; set; }
        public virtual proveedor proveedor { get; set; }
        public virtual Tipo_pago Tipo_pago { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pagos> Pagos { get; set; }
    }
}
