//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capa_Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Producto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Producto()
        {
            this.Detalle_cotizacion = new HashSet<Detalle_cotizacion>();
        }
    
        public int id_producto { get; set; }
        public Nullable<int> id_proveedor { get; set; }
        public string nombre { get; set; }
        public Nullable<decimal> precio_compra { get; set; }
        public Nullable<decimal> precio_venta { get; set; }
        public Nullable<int> can_existente { get; set; }
        public Nullable<int> num_lote { get; set; }
        public Nullable<int> id_categoria { get; set; }
    
        public virtual categorias categorias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Detalle_cotizacion> Detalle_cotizacion { get; set; }
        public virtual Inventario Inventario { get; set; }
        public virtual proveedor proveedor { get; set; }
    }
}
